# Generated by Django 3.2.23 on 2023-11-27 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('capacity', models.IntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(1, '12:00PM - 2:00PM'), (2, '2:00PM - 4:00PM'), (3, '4:00PM - 6:00PM'), (4, '6:00PM - 8:00PM'), (5, '8:00PM - 10:00PM')], default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('number_of_guests', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
